version: '3.4'

services:
  dictionary.webapi:
    image: ${DOCKER_REGISTRY-}dictionarywebapi
    build:
      context: .
      dockerfile: Crossword.WebAPI/Dockerfile

  game.webapi:
    image: ${DOCKER_REGISTRY-}gamewebapi
    build:
      context: .
      dockerfile: Term.WebAPI/Dockerfile
  
  db:
    image: mcr.microsoft.com/mssql/server  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "123456S3NH4S3CR3T4P@SSW0RD123456"