version: '3.4'

services:
  crossword.webapi:
    image: ${DOCKER_REGISTRY-}crosswordwebapi
    build:
      context: .
      dockerfile: Crossword.WebAPI/Dockerfile
    depends_on:
      - term.webapi
    ports:  
      - '25566:25566'  
    expose:  
      - 25566
    networks:
        default:
            aliases:
              - crossword.webapi

  term.webapi:
    image: ${DOCKER_REGISTRY-}termwebapi
    build:
      context: .
      dockerfile: Term.WebAPI/Dockerfile
    depends_on:
      - db
    ports:  
      - '25565:25565'  
    expose:  
      - 25565
    networks:
        default:
            aliases:
              - term.webapi

  db:
    image: mcr.microsoft.com/mssql/server  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "123456S3NH4S3CR3T4P@SSW0RD123456"
    ports:  
      - '1433:1433'  
    expose:  
      - 1433